### PUT request to example server
PUT http://localhost:4000/patients/1
Content-Type: application/json

{
  "name": "Jane nass",
  "email": "jane.smith@gmail.com",
    "adresse": "456 Oak St",
    "dateOfBirth": "1995-05-20",
    "registerDate": "2024-08-05"
}
###